### ISSUE TITLE
Build failed: Manifest merger failed 

### ISSUE THREAD

**Issue by havinhthai** [neuberoliveira/react-native-gps-state#10]
## Version
react: 16.3.1
react-native: 0.55.4
react-native-gps-state: 0.0.2

## Issue 

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:15:7-34
        is also present at [:react-native-gps-state] AndroidManifest.xml:15:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:11:5-77:19 to override.
```

**Comment by ismaserrano** [comment]
Add that attribute to Android manifest 'application' tag --> tools:replace="android:allowBackup". Then you have the previous error from override method (https://github.com/neuberoliveira/react-native-gps-state/issues/8), just comment it!

**Comment by lequangtuananh** [comment]
> Add that attribute to Android manifest 'application' tag --> tools:replace="android:allowBackup". Then you have the previous error from override method (#8), just comment it!

and then flow https://github.com/magus/react-native-facebook-login/issues/233#issuecomment-293251545

**Comment by mrigo** [comment]
I've followed your suggestions, but now I've
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:29:5-111:19 to override.
```

And I can't add another tools property to the application tag...
How can I fix that?

Thanks
\m

**Comment by lbelavoir** [comment]
@mrigo did you find any solution ?

**Comment by mrigo** [comment]
The problem was that some of my libraries don't support androidx and some others do.
So I've checked all my external libraries' gradle and change the version of playServices, trying to balance every library with what it needs... devastating but that's the only way...

**Comment by lbelavoir** [comment]
Thanks @mrigo I was hoping for an easier solution but I guess I'll have to do it too
