### ISSUE TITLE
initialize subscription in addListener

### ISSUE THREAD

**Issue by iliyanmotovski** [neuberoliveira/react-native-gps-state#14]
**What is the problem?**
If I want to remove the listener on every exit of my app, I cannot do so, as removeListener() is removing the subscription. This would be fine if i could initialize the subscription again up on starting the app.

**Proposed solution:**
Maybe initialize the subscription in addListener()

**Comment by neuberoliveira** [comment]
hi @iliyanmotovski thanks for the report, i make this plugin in my first days of rn, so there's a lot of weird things, sorry.

Iam migrating to RN0.56 to match new playstore rules, so i make some improvements and work a little in this issue, i dont have much time to test it deeply, but its working for my use case.

If you could test it ill be very glad.

**Comment by iliyanmotovski** [comment]
It works now, thanks.
