### ISSUE TITLE
GPSState.openLocationSettings failed

### ISSUE THREAD

**Issue by phamyqb** [neuberoliveira/react-native-gps-state#27]
When call GPSState.openLocationSettings(), on IOS show error: GPSState.openSettings was called with 1 arguments but expects 0 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away". How to fix this error ?

**Comment by huy-lv** [comment]
I fixed it, use this version
"@tootsweet/react-native-gps-state": "git+https://github.com/huy-lv/react-native-gps-state.git#master",
